### ISSUE TITLE
Add suppliers for generating Strings

### ISSUE THREAD

**Issue by ajoz** [foobaz42/teoria#18]
This task involves:
- creating annotations `@Strings`, `@AlphaStrings`, `@NumericStrings`, `@NonAlphaStrings`, ...
- it should be possible to control the minimal and maximal length of the string
- it should be possible to exclude certain characters from the strings
- it should be possible to limit the amount of strings generated
- strings should be unique
- empty string should not be generated more then once (if minimal length is 0)
- creating suppliers for these annotations

Questions
- Theory annotation allows for specifying if nulls are allowed. Should a particular supplier also give such support?

**Comment by GledsonAfonso** [comment]
Can I try this?

**Comment by ajoz** [comment]
Please feel free to try this. This task is probably too big for its own good. I usually like to deliver smaller chunks of work. So for example one annotation + supplier at a time but it is up to you.

**Comment by GledsonAfonso** [comment]
Okay, I'll try to code one by one then and see if I can make it. Thanks!

**Comment by ajoz** [comment]
You will see how the work goes and if you will feel that more fine grained tasks are needed, we will split this up to smaller chunks.

**Comment by GledsonAfonso** [comment]
I'll keep you updated then. Thanks again.

**Comment by GledsonAfonso** [comment]
Sorry for the late feedback. About splitting the issue into separate minor issues to be solved, I think it would be a better idea to do so, mostly if it aims beginners (as I think it does). I will try and do `@Strings` to get a gist of it.

**Comment by ajoz** [comment]
Sorry for late feedback ;-) I had a lot on my head recent weeks, this is why I could not get back to you immediately. I've created a smaller scope ticket with an example:
https://github.com/artificialrevelations/teoria/issues/20

**Comment by GledsonAfonso** [comment]
Hey, no problem! Thanks for creating a new issue. So how do we do, now? Do I keep working on @Strings?

**Comment by ajoz** [comment]
I will split it up into several smaller tasks today and will close it. It will be much easier to manage the work then.

**Comment by ajoz** [comment]
I've initially split the task into 3 separate tasks:
- `@Strings` - https://github.com/artificialrevelations/teoria/issues/22
- `@NumericStrings` - https://github.com/artificialrevelations/teoria/issues/20
- `@AlphaStrings` - https://github.com/artificialrevelations/teoria/issues/21

Each of these tasks has a "minimal scope" and I would advise to focus on it even if the code would not be generic or reusable enough.

@GledsonAfonso Please pick whichever you find interesting.

**Comment by GledsonAfonso** [comment]
Okay, thanks!
